apiVersion: v1
kind: Service
metadata:
  name: sentinelai-backend
  namespace: sentinelai
spec:
  selector:
    app: sentinelai-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
