apiVersion: v1
kind: Service
metadata:
  name: sentinelai-frontend
  namespace: sentinelai
spec:
  selector:
    app: sentinelai-frontend
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer

spec:
  nodeSelector:
    nvidia.com/gpu.present: "true"
